### PR TITLE
HOOBS Certification

### PR DESCRIPTION
**Pull request by BobbySlope**
Hello @howanghk 

We like to inform you that we have certified your Plugin directly for HOOBS as we no longer fork the plugin to certify it.

Your Plugin is set to automatically certify the Latest version you push to npm.

**Heres the Plugin site of your Plugin:**
https://plugins.hoobs.org/plugin/homebridge-ewelink-max

_HOOBS Tab - shows the HOOBS customised Readme
Homebridge Tab - shows your Readme on npm_

Users can also write reviews there and we plan to extend it with an Plugin based forum.

All support will be done by HOOBS, and you can direct any HOOBS Users to our Support site:
http://support.hoobs.org

We will check if its an Issue related to HOOBS or an issue with the Plugin itself. If the second is the case we will contact you via issues on your GitHub repo.

We added two badges to your readme:

[certified-hoobs-plugin](https://plugins.hoobs.org) [hoobs-support](https://support.hoobs.org)

Regards

Bobby @hoobs-org

### CODE REVIEW

**Comment by fizulnizam** [comment]
Please update the plugin on HOOBS to 0.1.24

**Comment by BobbySlope** [comment]
Plugins caches each 12h so update will be available soon. 
Thanks for merging

**Comment by BobbySlope** [comment]
@howanghk please send us an email at plugindev@hoobs.org and we can invite you to our slack

**Comment by fizulnizam** [comment]
@BobbySlope It has been more than 12 hours now but the update is still not showing in HOOBS :(

**Comment by fizulnizam** [comment]
Still no update in the plugin section..

**Comment by BobbySlope** [comment]
its now synced: https://plugins.hoobs.org/plugin/homebridge-ewelink-max

**Pull request merged**
